-- MySQL Script generated by MySQL Workbench
-- Wed Mar 31 09:48:17 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema online_bookstore
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `online_bookstore` ;

-- -----------------------------------------------------
-- Schema online_bookstore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `online_bookstore` DEFAULT CHARACTER SET utf8 ;
USE `online_bookstore` ;

-- -----------------------------------------------------
-- Table `online_bookstore`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_bookstore`.`book` ;

CREATE TABLE IF NOT EXISTS `online_bookstore`.`book` (
  `book_ISBN` VARCHAR(45) NOT NULL,
  `book_author` VARCHAR(45) NOT NULL,
  `book_publisher` VARCHAR(45) NOT NULL,
  `book_title` VARCHAR(45) NOT NULL,
  `book_language` VARCHAR(45) NULL,
  `book_price_gbp` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`book_ISBN`),
  UNIQUE INDEX `book_ISBN_UNIQUE` (`book_ISBN` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_bookstore`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_bookstore`.`customer` ;

CREATE TABLE IF NOT EXISTS `online_bookstore`.`customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `customer_phone` VARCHAR(45) NOT NULL,
  `customer_name` VARCHAR(45) NOT NULL,
  `customer_address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_bookstore`.`delivery_co`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_bookstore`.`delivery_co` ;

CREATE TABLE IF NOT EXISTS `online_bookstore`.`delivery_co` (
  `delivery_co_reg_no` INT NOT NULL,
  `delivery_co_reg_date` DATE NOT NULL,
  `delivery_co_contract_end` DATE NOT NULL,
  `delivery_co_charge_gbp` INT NULL,
  PRIMARY KEY (`delivery_co_reg_no`),
  UNIQUE INDEX `delivery_co_reg_no_UNIQUE` (`delivery_co_reg_no` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_bookstore`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_bookstore`.`order` ;

CREATE TABLE IF NOT EXISTS `online_bookstore`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `order_customer_id` INT NOT NULL,
  `order_date_placed` DATETIME NOT NULL,
  `order_placed_via` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `customer_who_ordered_idx` (`order_customer_id` ASC) VISIBLE,
  CONSTRAINT `customer_who_ordered`
    FOREIGN KEY (`order_customer_id`)
    REFERENCES `online_bookstore`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_bookstore`.`delivery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_bookstore`.`delivery` ;

CREATE TABLE IF NOT EXISTS `online_bookstore`.`delivery` (
  `delivery_id` INT NOT NULL AUTO_INCREMENT,
  `delivery_time` DATETIME NOT NULL,
  `delivery_staff_id` INT NOT NULL,
  `delivery_order_id` INT NOT NULL,
  `delivery_co_reg_no` INT NOT NULL,
  PRIMARY KEY (`delivery_id`),
  INDEX `order_id_idx` (`delivery_order_id` ASC) VISIBLE,
  INDEX `del_cp_id_idx` (`delivery_co_reg_no` ASC) VISIBLE,
  CONSTRAINT `order_id`
    FOREIGN KEY (`delivery_order_id`)
    REFERENCES `online_bookstore`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `del_cp_id`
    FOREIGN KEY (`delivery_co_reg_no`)
    REFERENCES `online_bookstore`.`delivery_co` (`delivery_co_reg_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_bookstore`.`order_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_bookstore`.`order_details` ;

CREATE TABLE IF NOT EXISTS `online_bookstore`.`order_details` (
  `order_details_id` INT NOT NULL AUTO_INCREMENT,
  `order_details_order_id` INT NOT NULL,
  `order_details_qty` INT NOT NULL,
  `order_details_book_isbn` VARCHAR(45) NOT NULL,
  INDEX `order_id_idx` (`order_details_order_id` ASC) VISIBLE,
  PRIMARY KEY (`order_details_id`),
  INDEX `isbn_idx` (`order_details_book_isbn` ASC) VISIBLE,
  CONSTRAINT `order_id_of_order`
    FOREIGN KEY (`order_details_order_id`)
    REFERENCES `online_bookstore`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `isbn`
    FOREIGN KEY (`order_details_book_isbn`)
    REFERENCES `online_bookstore`.`book` (`book_ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
